print('DESAFIO 004')
print()
x = input('Digite algo: ')
print(type(x))
print('É alphanumerico?', x.isalpha())
print('É um número?', x.isalnum())
print('Tem espaços?', x.isspace())
print('Está em munúsculo?', x.islower())
print('Está em maiúsculo?', x.isupper())
print('Está capitalizada?', x.istitle())