print('DESAFIO 09')
print()
print('==========TABUADA INTERATIVA==========')
print()
n = int(input('Digite um número: '))
print('-' *12)
print('ADIÇÃO')
print('{} + {} = {}'.format(n, 1, n+1))
print('{} + {} = {}'.format(n, 2, n+2))
print('{} + {} = {}'.format(n, 3, n+3))
print('{} + {} = {}'.format(n, 4, n+4))
print('{} + {} = {}'.format(n, 5, n+5))
print('{} + {} = {}'.format(n, 6, n+6))
print('{} + {} = {}'.format(n, 7, n+7))
print('{} + {} = {}'.format(n, 8, n+8))
print('{} + {} = {}'.format(n, 9, n+9))
print('{} + {} = {}'.format(n, 10, n+10))
print('-' *12)
print('SUBTRAÇÃO')
print('{} - {} = {}'.format(n, 1, n-1))
print('{} - {} = {}'.format(n, 2, n-2))
print('{} - {} = {}'.format(n, 3, n-3))
print('{} - {} = {}'.format(n, 4, n-4))
print('{} - {} = {}'.format(n, 5, n-5))
print('{} - {} = {}'.format(n, 6, n-6))
print('{} - {} = {}'.format(n, 7, n-7))
print('{} - {} = {}'.format(n, 8, n-8))
print('{} - {} = {}'.format(n, 9, n-9))
print('{} - {} = {}'.format(n, 10, n-10))
print('-' *12)
print('MULTIPLICAÇÃO')
print('{} x {} = {}'.format(n, 1, n*1))
print('{} x {} = {}'.format(n, 2, n*2))
print('{} x {} = {}'.format(n, 3, n*3))
print('{} x {} = {}'.format(n, 4, n*4))
print('{} x {} = {}'.format(n, 5, n*5))
print('{} x {} = {}'.format(n, 6, n*6))
print('{} x {} = {}'.format(n, 7, n*7))
print('{} x {} = {}'.format(n, 8, n*8))
print('{} x {} = {}'.format(n, 9, n*9))
print('{} x {} = {}'.format(n, 10, n*10))
print('-' *12)
print('DIVISÃO')
print('{} / {} = {:.2f}'.format(n, 1, n/1))
print('{} / {} = {:.2f}'.format(n, 2, n/2))
print('{} / {} = {:.2f}'.format(n, 3, n/3))
print('{} / {} = {:.2f}'.format(n, 4, n/4))
print('{} / {} = {:.2f}'.format(n, 5, n/5))
print('{} / {} = {:.2f}'.format(n, 6, n/6))
print('{} / {} = {:.2f}'.format(n, 7, n/7))
print('{} / {} = {:.2f}'.format(n, 8, n/8))
print('{} / {} = {:.2f}'.format(n, 9, n/9))
print('{} / {} = {:.2f}'.format(n, 10, n/10))
print('-' *12)