print('DESAFIO 06')
print()
n = int(input('Digite um numero: '))
print('O dobro de {} vale {}'.format(n, (n*2)))
print('O triplo de {} vale {}'.format(n, (n*3)))
print('A raiz quadrada de {} é {:.2f}'.format(n, n**(1/2)))